{% set name = "rtree" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6b1b3550881e57ebe530cc6cffefc87cd9bf49c30b37b894065a9f810875e46

build:
  number: 1
  skip: True  # [py<39]
  # No need to set special variables for the DLL library path, as current version of the package will already look for the
  # dynamic library in conda path when using conda: https://github.com/Toblerity/rtree/blob/1.4.1/rtree/finder.py#L39
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - wheel
    - libspatialindex {{ libspatialindex }}
  run:
    - python
    # Dependencies described here:
    # https://github.com/Toblerity/rtree/blob/1.4.1/DEPENDENCIES.txt
    - libspatialindex >=1.8.5

test:
  # Imports are in run_test.py
  source_files:
    - tests
  requires:
    - pip
    - pytest >=6
    - numpy
  commands:
    - pip check
    - pytest --import-mode=importlib -vv tests

about:
  home: https://github.com/Toblerity/rtree
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS
  description: |
    Rtree is a ctypes Python wrapper of libspatialindex 
    that provides a number of advanced spatial indexing features for the spatially curious Python user. 
  dev_url: https://github.com/Toblerity/rtree
  doc_url: https://rtree.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
