{% set version = "0.8.3" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Rtree/Rtree-{{ version }}.tar.gz
  sha256: 6cb9cf3000963ea6a3db777a597baee2bc55c4fc891e4f1967f262cc96148649
  patches:
    - find_libray.patch
    - setup-win.path  # [win]
    - find_libray-win32.patch  # [win32]

build:
  number: 1002
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]

requirements:
  host:
    - python
    - pip
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: http://toblerity.github.com/rtree/
  license: LGPL-2.1
  license_file: LICENSE.txt
  summary: 'R-Tree spatial index for Python GIS'

extra:
  recipe-maintainers:
    - ocefpaf
