{% set name = "rtree" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6b1b3550881e57ebe530cc6cffefc87cd9bf49c30b37b894065a9f810875e46

build:
  number: 0
  skip: True  # [py<39 or (win and vc<14)]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - wheel
  run:
    - python
    # Dependencies described here:
    # https://github.com/Toblerity/rtree/blob/1.4.1/DEPENDENCIES.txt
    - libspatialindex >=1.8.5

test:
  # Imports are in run_test.py
  #imports:
  #  - rtree
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Toblerity/rtree
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS
  description: |
    Rtree is a ctypes Python wrapper of libspatialindex 
    that provides a number of advanced spatial indexing features for the spatially curious Python user. 
  dev_url: https://github.com/Toblerity/rtree
  doc_url: https://rtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
