travis:
  secure:
    BINSTAR_TOKEN: mnoGXaxcurBio8TTU/tibkjxIo4T87kegvmBka53/jnZhEIMxqc3uOakm6WBExVNbKwemRtb0+r1V8F9/ZYghvPBPRZ8Nui5alXPDbsXVrom0dwE3YDrMziT9kZ9op6NIwHLShcBAwj7XZb/Io1RgmS5Jsp19kn32+JMO95hYp7+6X/jA07wvCUtogMi7991FvOiA6SM38RuHiAFi3TBngl0lT3XW5VQvgK84p/u2zBT/MJLbZ8kC+6ciJqmeqC4OpI2p/25aYZbaH8nXjekS8DvH4sPI2GC53GYy2tol5Mn3IV4dwYGkKTNWHOdEsV9gl1Z2aVCh02N+rOX7daCMwPQK3fcpl+E7xcdzmAc/fSEQz8g8r2NNepEKjhG2CTqaGQzbzsl9bxgwcrzglOT0DBpxtWzIPsJcq6sVKaAPqcvCEz8H2JcUgIaLlSQ+kirLUeGdnwf0ErpHKfteimJTAi88rf/ssZUXavDjL20gV0+oHH6tQSIl9RXJVawgqo9OYZA1DDewlnhwakwxGrTNJagA1LfaofCl4zL/jwcSQpg49hNiPb1NwVbPEbH7bvZD1I4/z77ZLlvxpYk6T0Fo0wxzjatv7auS3sQwpyBMzWaz05EOyk4wqRClv3/5U9zyEjRKpdaKOcUX3f3SDG6c87Haed6Mk5EWBgCkPT9oF8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
